name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: Features
    collapse-after: 0
    labels:
      - 'enhancement'
  - title: Bug Fixes
    labels:
      - 'bug'
  - title: Maintenance
    labels:
      - 'chore'
      - 'documentation'
  - title: Miscellaneous
    labels:
      - 'misc'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: patch
include-labels:
  - 'breaking-change'
  - 'enhancement'
  - 'bug'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes
  $CHANGES
replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'misc'
    title:
      - '/misc:.+/i'
  - label: 'chore'
    title:
      - '/chore:.+/i'
  - label: 'enhancement'
    title:
      - '/feat/i'
    branch:
      - '/feature\/.+/'