name: Debian Package Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Container Image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            notimportant
          tags: |
            type=pep440,pattern={{version}}
            type=ref,event=branch,prefix=0.0.0-
            type=ref,event=pr,prefix=0.0.0-pr-
            type=sha,prefix=0.0.0-sha-

      - uses: jiro4989/build-deb-action@v2
        with:
          package: unifi-tailscale-ip-rule-monitor
          package_root: .debpkg
          maintainer: Joel Cressy
          version: ${{ steps.meta.outputs.version }}
          arch: 'all'
          depends: 'tailscale'
          desc: |
            Unifi IP Rule Monitor for Tailscale

      - name: Get Release Asset
        id: get_release_asset
        run: |-
          echo "asset_path=$(echo ./*_all.deb)" >> $GITHUB_OUTPUT
          echo "asset_name=$(basename ./*_all.deb)" >> $GITHUB_OUTPUT
          echo "asset_content_type=$(file --brief --mime-type ./*_all.deb)" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.get_release_asset.outputs.asset_path }}
          asset_name: ${{ steps.get_release_asset.outputs.asset_name }}
          asset_content_type: ${{ steps.get_release_asset.outputs.asset_content_type }}